move test_latest_imagestreams case into openshift tests
sclorg/s2i-perl-container pull request #187
Opened 2020-09-25 11:52 UTC by pkubatrh

2020-09-25 11:53 UTC, pkubatrh commented
[test-openshift]

2020-09-25 12:38 UTC, ppisar commented
No problem from Perl point of view.

2020-09-29 08:09 UTC, phracek commented
Please remove from `${VERSIONS}/test/run` function `test_latest_imagestreams`.

2020-09-29 08:10 UTC, phracek requested changes
Thanks for the PR! `test_latest_imagestreams` function was not moved from ${VERSIONS}/test/run. Please move it.

2020-09-29 08:10 UTC, phracek commented on test/run-openshift
> +test_latest_imagestreams
The function `test_latest_imagestreams` is a wrapper around `ct_check_latest_imagestreams`.

2020-09-29 08:10 UTC, phracek commented on test/run-openshift
> +# check if latest imagestream version is correct
```suggestion
# check if latest imagestream version is correct
test_latest_imagestreams() {
  local result=1
  info "Testing the latest version in imagestreams"
  # Switch to root directory of a container
  pushd "${test_dir}/../.." >/dev/null || return 1
  ct_check_latest_imagestreams
  result=$?
  popd >/dev/null || return 1
  check_result $result
}
```

2020-10-22 07:53 UTC, pkubatrh commented on test/run-openshift
> +test_latest_imagestreams
Thanks for spotting this. for some reason I thought this is coming from the test-lib even though it does not have a ct prefix :/ Should be fixed now.

2020-10-22 07:54 UTC, pkubatrh commented
[test-openshift]

2020-10-22 07:58 UTC, pkubatrh commented
[test-openshift]

2020-10-22 11:33 UTC, pkubatrh commented
[test-openshift]

2020-10-23 12:02 UTC, phracek approved these changes
LGTM. Thanks for the PR!. Good work.

2020-10-23 12:02 UTC, merged