enable scl variables
sclorg/s2i-perl-container pull request #198
Opened 2020-11-18 18:01 UTC by fila43

enable scl env variable, based on that is not necessary to use versioned from-dockerfiles examples

2020-11-18 18:02 UTC, fila43 commented
[test]

2020-11-18 18:38 UTC, fila43 commented
[test]

2020-11-19 11:25 UTC, ppisar commented
If you preset SCL environment variables on Dockerfile level as if "scl enable" was invoked, all invocations of "scl enable" could be removed. It would be great to delete:

* root/opt/app-root/etc/scl_enable files
* "ENV BASH_ENV" line from the Dockerfiles

2020-11-20 09:02 UTC, pkubatrh commented
> If you preset SCL environment variables on Dockerfile level as if "scl enable" was invoked, all invocations of "scl enable" could be removed. It would be great to delete:

True, though the tests for this feature set the use case when `bash` is called inside the image as a correct (thanks to `scl_enable`) baseline to check against, so they would need to be rewritten to be a bit smarter (by providing list of expected SCLs enabled provided in the image's test suite for example) if we wanted to remove the `scl_enable` files entirely.
I wonder if the `scl_enable` files might possibly used by some of our advanced users. I do not think we document it anywhere so I find it unlikely, but would still see removing the files as a bit of a risk because of this as well.

2020-11-20 12:50 UTC, fila43 commented
[test]

2020-11-23 10:28 UTC, fila43 commented
It sounds fine, but do you see removing this stuff necessary for now?  From my point of view, the worst case is enabling scl twice. And only centos7 and rhel7 are affected. I think it should be removed later, together with all other containers.

2020-12-15 16:21 UTC, ppisar commented
My point is that you make it more complicated and that keeping the scl_enable call masks all mistakes you can do in the Dockerfiles.

2020-12-15 16:30 UTC, ppisar commented on 5.26/Dockerfile
> +     PATH=$PATH:/opt/rh/$NODEJS_SCL/root/usr/bin:/opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/
Duplicated values:

/opt/rh/httpd24/root/usr/bin
/opt/rh/httpd24/root/usr/sbin

Is /opt/rh/$NODEJS_SCL/root/usr/bin and /opt/rh/$SCL_NODEJS/root/usr/bin diffrent?

/opt/rh-perl526/root/bin should be spelled with $PERL_SHORT_VER.

A path for user-installed executables, /opt/app-root/src/extlib/bin, is missing.

2020-12-15 16:31 UTC, ppisar commented on 5.26/Dockerfile
> +     X_SCLS=rh-perl$PERL_SHORT_VER \
httpd24 and $NODEJS_SCL is missing from X_SCLS.

2020-12-15 16:33 UTC, ppisar commented on 5.26/Dockerfile
> +     LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64 \
rh-perl$PERL_SHORT_VER and $NODEJS is misssing from LIBRARY_PATH.

2020-12-15 16:34 UTC, ppisar commented on 5.26/Dockerfile
> +     MANPATH=/opt/rh/$NODEJS_SCL/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man
rh-perl$PERL_SHORT_VER is missing from MANPATH

2020-12-15 16:35 UTC, ppisar commented on 5.26/Dockerfile
PERL5LIB=/opt/app-root/src/extlib/lib/perl5 for user-installed Perl modules is missing.

2020-12-15 16:36 UTC, ppisar commented on 5.26/Dockerfile.rhel7
> +     MANPATH=/opt/rh/$NODEJS_SCL/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man
The same issues as in 5.26/Dockerfile.

2020-12-15 16:38 UTC, ppisar commented on 5.30/Dockerfile
> +     MANPATH=/opt/rh/$NODEJS_SCL/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man
The same issues as in 5.26/Dockerfile.

2020-12-15 16:38 UTC, ppisar commented on 5.30/Dockerfile.rhel7
> +     MANPATH=/opt/rh/$NODEJS_SCL/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man
The same issues as in 5.26/Dockerfile.

2021-02-18 09:25 UTC, fila43 commented on 5.26/Dockerfile
It could be added, but actually scl_enable doesn't enable this path

2021-02-18 09:29 UTC, fila43 commented on 5.26/Dockerfile
> +     LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64 \
Is it necessary? Because scl_enable doesn't add rh-perl$PERL_SHORT_VER and $NODEJS into LIBRARY_PATH

2021-02-18 12:45 UTC, ppisar commented on 5.26/Dockerfile
> +     LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64 \
Of course "scl enable rh-perl526" amends LD_LIBRARY_PATH:

~~~~
# echo $LD_LIBRARY_PATH

# scl enable rh-perl526 'echo $LD_LIBRARY_PATH'
/opt/rh/rh-perl526/root/usr/lib64
~~~~

2021-02-18 12:51 UTC, ppisar commented on 5.26/Dockerfile
You are right that scl_enable does not do that. It is done in s2i/bin/run script. But I thought that a purpose of your change is have the same environment in both run and exec container modes. Without the paths Perl modules and scripts installed at the time of building an application image won't be available in the exec mode.

2021-02-18 15:46 UTC, fila43 commented on 5.26/Dockerfile
> +     LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64 \
I agree  LD_LIBRARY_PATH contains rh-perl526, but LIBRARY_PATH doesn't.

2021-02-18 16:01 UTC, fila43 commented on 5.26/Dockerfile
ok thanks, that make sense

2021-02-22 09:04 UTC, fila43 commented
[test]

2021-02-22 10:17 UTC, phracek requested changes

2021-02-22 10:17 UTC, phracek commented on 5.26/Dockerfile
> +ENV BASH_ENV \
BASH_ENV is a dummy variable? Can it be removed? I have lost the content here.

2021-02-22 10:17 UTC, phracek commented on 5.26/Dockerfile
> +     LD_LIBRARY_PATH=/opt/rh/$NODEJS_SCL/root/usr/lib64:/opt/rh/rh-perl$PERL_SHORT_VER/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64 \
httpd24 is defined several times. What about defining a variable like HTTPD_24=httpd24 and then use only $HTTPD_24?

2021-02-22 10:17 UTC, phracek commented on 5.26/Dockerfile.rhel7
> +     PKGG_CONFIG_PATH=/opt/rh/httpd24/root/usr/lib64/pkgconfig \
The same here with httpd24 like before.

2021-02-22 10:17 UTC, phracek commented on test/run
> + fi
`space` is missing. Just bash style.

2021-02-22 10:18 UTC, phracek commented
Thanks for driving this PR!. Cool.

2021-02-22 12:08 UTC, fila43 commented on test/run
> + fi
Thanks for the notes!

2021-02-22 12:08 UTC, fila43 commented
[test]

2021-02-23 08:36 UTC, fila43 commented
@ppisar now it should be ready, I have disabled scl_enable, so paths shouldn't be duplicated and I have also enabled PERL5LIB, current env output should look the same as after the application of scl_enable.

2021-02-24 09:41 UTC, ppisar commented
I can see you set PERL5LIB=/opt/app-root/src/extlib/lib/perl5, but you don't
add /opt/app-root/src/extlib/bin into PATH. Please add it to PATH and remove
the the two settings at the beggining of s2i/bin/run.

2021-02-24 11:48 UTC, fila43 commented
[test]

2021-02-24 16:46 UTC, ppisar commented
I can see that the tests passed in RHEL and CenOS. Fedora does not have
software collection, so the failure is expected. If you are ready, you can
merge it.

2021-02-24 17:36 UTC, fila43 commented
ok, great, I looked at Fedora and it seems that adding PERL5LIB=/opt/app-root/src/extlib/lib/perl5 and /opt/app-root/src/extlib/bin into PATH  helps and tests pass, what is your opinion in case of adding this stuff into Fedora's dockerfile.

2021-02-25 10:57 UTC, ppisar commented
There is no perl 5.26 in Fedora. There is perl 5.30 in Fedora 32, but it isn't
in Fedora 33 which is used in the Dockerfiles now. Thus having any Dockerfiles
for Fedora does not make sense. If you built such a Perl image, it would be
a lie because a name of image would not match perl inside.

2021-03-02 09:31 UTC, phracek commented
> There is no perl 5.26 in Fedora. There is perl 5.30 in Fedora 32, but it isn't in Fedora 33 which is used in the Dockerfiles now. Thus having any Dockerfiles for Fedora does not make sense. If you built such a Perl image, it would be a lie because a name of image would not match perl inside.

As far as I know, F31 and F32 contain perl-30. We can change Dockerfile into f32/s2i-base. But this does not bring any new things.
It would be great to have Fedora tests passing as well. :)

2021-03-02 09:33 UTC, phracek commented
> I can see that the tests passed in RHEL and CenOS. Fedora does not have software collection, so the failure is expected. If you are ready, you can merge it.

You are right, Fedora does not have softw are collections, but it uses standard perl distributions, e.g. 5-30 in F31 and F32. 
Dockerfile.fedora is not changed, thus Failure is not expected.

2021-03-02 11:43 UTC, ppisar commented
I see. Then add setting the variables in Dockerfile.fedora.

2021-03-03 08:01 UTC, fila43 commented
[test]

2021-03-03 10:33 UTC, ppisar commented
Great. Can I merge it?

2021-03-03 10:37 UTC, fila43 commented
Yes, now it's ready, thanks for your cooperation!

2021-03-03 10:38 UTC, merged