change usage script, add openshift usage
sclorg/s2i-perl-container pull request #200
Opened 2020-12-02 11:54 UTC by fila43

2020-12-02 11:54 UTC, fila43 commented
[test]

2020-12-15 08:18 UTC, ppisar commented on 5.26-mod_fcgid/s2i/bin/usage
> +oc new-app perl:5.26-~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.26/test/sample-test-app/
Is the hyphen in "perl:5.26-" correct?

2020-12-15 08:24 UTC, ppisar commented on 5.26-mod_fcgid/s2i/bin/usage
> +oc new-app perl:5.26-~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.26/test/sample-test-app/
A documentation for 5.26-mod_fcgid should use --context-dir=5.26-mod_fcgid/...

2020-12-15 08:27 UTC, ppisar commented on 5.30-mod_fcgid/s2i/bin/usage
> +oc new-app perl:5.30~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.30/test/sample-test-app/
A documentation for 5.30-mod_fcgid should use --context-dir=5.30-mod_fcgid/...

2020-12-15 08:33 UTC, ppisar commented
The patch replaces s2i usage with OpenShift usage. Please rephrase to commit message like that.
Also I have zero knowledge about OpenShift. Please consult with @phracek or @hhorak.

2020-12-15 11:07 UTC, fila43 commented
[test]

2020-12-15 11:17 UTC, phracek requested changes
Only some version replacement with an environment variable. Thanks for the PR!.

2020-12-15 11:17 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/usage
> +oc new-app perl:5.26~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.26-mod_fcgid/test/sample-test-app/
```suggestion
oc new-app perl:${PERL_VERSION}~https://github.com/sclorg/s2i-perl-container.git --context-dir=${PERL_VERSION}-mod_fcgid/test/sample-test-app/
```

2020-12-15 11:17 UTC, phracek commented on 5.26/s2i/bin/usage
> +https://github.com/sclorg/s2i-perl-container/blob/master/5.26/README.md
```suggestion
https://github.com/sclorg/s2i-perl-container/blob/master/${PERL_VERSION}/README.md
```

2020-12-15 11:17 UTC, phracek commented on 5.26/s2i/bin/usage
> +oc new-app perl:5.26~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.26/test/sample-test-app/
```suggestion
oc new-app perl:${PERL_VERSION}~https://github.com/sclorg/s2i-perl-container.git --context-dir=${PERL_VERSION}/test/sample-test-app/
```

2020-12-15 11:17 UTC, phracek commented on 5.30-mod_fcgid/s2i/bin/usage
> +https://github.com/sclorg/s2i-perl-container/blob/master/5.30-mod_fcgid/README.md
```suggestion
https://github.com/sclorg/s2i-perl-container/blob/master/${PERL_VERSION}-mod_fcgid/README.md
```

2020-12-15 11:17 UTC, phracek commented on 5.30-mod_fcgid/s2i/bin/usage
> +oc new-app perl:5.30~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.30-mod_fcgid/test/sample-test-app/
```suggestion
oc new-app perl:${PERL_VERSION}~https://github.com/sclorg/s2i-perl-container.git --context-dir=${PERL_VERSION}-mod_fcgid/test/sample-test-app/
```

2020-12-15 11:17 UTC, phracek commented on 5.30/s2i/bin/usage
> +https://github.com/sclorg/s2i-perl-container/blob/master/5.30/README.md
```suggestion
https://github.com/sclorg/s2i-perl-container/blob/master/${PERL_VERSION}/README.md
```

2020-12-15 11:17 UTC, phracek commented on 5.30/s2i/bin/usage
> +oc new-app perl:5.30~https://github.com/sclorg/s2i-perl-container.git --context-dir=5.30/test/sample-test-app/
```suggestion
oc new-app perl:${PERL_VERSION}~https://github.com/sclorg/s2i-perl-container.git --context-dir=${PERL_VERSION}/test/sample-test-app/
```

2020-12-15 11:17 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/usage
> +https://github.com/sclorg/s2i-perl-container/blob/master/5.26-mod_fcgid/README.md
```suggestion
https://github.com/sclorg/s2i-perl-container/blob/master/${PERL_VERSION}-mod_fcgid/README.md
```

2020-12-15 11:39 UTC, fila43 commented
thanks for the review, now it should be fine

2020-12-15 11:39 UTC, ppisar commented
Good.

2020-12-15 11:39 UTC, fila43 commented
[test]

2020-12-16 08:36 UTC, merged