Support PSGI reload
sclorg/s2i-perl-container pull request #236
Opened 2022-05-19 16:46 UTC by michal-josef-spacek

Again rebase of https://github.com/sclorg/s2i-perl-container/pull/221

2022-05-19 16:47 UTC, michal-josef-spacek commented
[test]

2022-05-19 17:48 UTC, yselkowitz commented
IIUC the hot deploy option for the other languages, including perl with mod_perl, is a runtime variable.  IOW `s2i/bin/run` looks for an environment variable (provided by the container runtime) and then modifies how the interpreter is executed accordingly, but a rebuild is not required.  However, this differs from all of those by requiring the decision to be made at build time.  Is there a way to rework this to not require rebuilding?

2022-05-19 19:19 UTC, michal-josef-spacek commented
@yselkowitz ok, good point. I will look to it.

2022-05-23 08:44 UTC, phracek commented
Why do you close #221 and create a newer one?

2022-05-23 09:10 UTC, phracek commented
[test-all]

2022-05-23 09:18 UTC, michal-josef-spacek commented
@phracek I rebased this PR to upstream and I created force push of PR. Force push closed PR, I don't know why.

2022-05-23 10:05 UTC, michal-josef-spacek commented
Heh I totally missed possibility of reopening.

2022-05-24 07:26 UTC, phracek requested changes

2022-05-24 07:26 UTC, phracek commented on 5.30-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R /opt/app-root/src/ "
`/opt/app-root/` is a variable $APP_ROOT https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.fedora#L29
or `/opt/app-root` is a variable $HOME https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.fedora#L31.

2022-05-24 07:26 UTC, phracek commented on test/run-modfcgid
> +    do_test 'psgi-hot_deploy' 'test_7_response' \
`psgi-hot_deploy` is a dir name in this upstream project. I guess you missed it adding it into s2i-perl-container repo. Like this https://github.com/sclorg/s2i-perl-container/blob/master/5.30/test/binpath, which is called here https://github.com/sclorg/s2i-perl-container/blob/master/test/run#L295

2022-05-24 07:26 UTC, phracek commented on test/run-modfcgid
> +    do_test 'psgi-hot_deploy' 'test_7_response' \
`psgi-hot_deploy` is a dir name in this upstream project. I guess you missed it adding it into s2i-perl-container repo. Like this https://github.com/sclorg/s2i-perl-container/blob/master/5.30/test/binpath, which is called here https://github.com/sclorg/s2i-perl-container/blob/master/test/run#L295

2022-05-27 19:36 UTC, michal-josef-spacek commented on test/run-modfcgid
> +    do_test 'psgi-hot_deploy' 'test_7_response' \
Yes, i created somehow this directory as submodule and don't deliver application :-/

2022-05-27 19:36 UTC, michal-josef-spacek commented
[test]

2022-05-27 20:06 UTC, michal-josef-spacek commented
TODO: Move PSGI_RELOAD from assembly to run.

2022-05-30 07:07 UTC, phracek commented
[test-all]

2022-05-31 13:27 UTC, michal-josef-spacek commented
[test]

2022-05-31 14:09 UTC, phracek commented
Container tests are green.

[test-openshift]

2022-05-31 14:09 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
I would prefer to delete space here and add it later on.

2022-05-31 14:10 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +    FcgidWrapper "/opt/app-root/psgiwrapper /usr/bin/env plackup $PLACKUP_ARGS-s FCGI $PSGI_FILE" virtual
The bash format does not look like well. 
```suggestion
    FcgidWrapper "/opt/app-root/psgiwrapper /usr/bin/env plackup $PLACKUP_ARGS -s FCGI $PSGI_FILE" virtual
```

2022-05-31 14:10 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
```suggestion
  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/"
```

2022-05-31 14:10 UTC, phracek commented on 5.30-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
The same here:
```suggestion
  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/"
```

2022-05-31 14:24 UTC, michal-josef-spacek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
In your case, there will be "␣␣" in case of PLACKUP_ARGS=""
In the case of PLACKUP_ARGS="-r -R ${APP_ROOT}/src/" will be with one ␣ between command arguments.

2022-05-31 15:41 UTC, michal-josef-spacek commented
[test]

2022-05-31 16:23 UTC, michal-josef-spacek commented
[test-all]

2022-05-31 17:19 UTC, michal-josef-spacek commented
@yselkowitz Seems that this is functional as you need.

2022-06-01 08:33 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +    FcgidWrapper "${APP_ROOT}/psgiwrapper /usr/bin/env plackup \${PLACKUP_ARGS}-s FCGI $PSGI_FILE" virtual
If the $PLACKUP_ARGS are not used in assemble scripts, then can be deleted, right?

2022-06-01 08:42 UTC, michal-josef-spacek commented
> I don't follow, why you have moved PLACKUP_ARGS from `assemble` to `run`? Can you please describe it a bit more?

https://github.com/sclorg/s2i-perl-container/pull/236#issuecomment-1132009513

2022-06-01 11:20 UTC, phracek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
You are right, there will be two spaces but the code looks better.

2022-06-01 11:28 UTC, michal-josef-spacek commented on 5.26-mod_fcgid/s2i/bin/assemble
> +  PLACKUP_ARGS="-r -R ${APP_ROOT}/src/ "
Ok, I will rewrite it to your version. 

In my experience I didn't like outputs that have more spaces, this seems like an issue.

2022-06-01 11:32 UTC, michal-josef-spacek commented
[test-all]

2022-06-02 10:06 UTC, phracek approved these changes
LGTM. Thanks for the PR!

2022-06-02 10:06 UTC, merged