Support perl 5.34 and Fedora
sclorg/s2i-perl-container pull request #244
Opened 2022-06-02 11:06 UTC by michal-josef-spacek

2022-06-02 11:06 UTC, michal-josef-spacek commented
[test]

2022-06-02 11:56 UTC, michal-josef-spacek commented
[test-all]

2022-06-06 07:55 UTC, phracek requested changes
Thanks for adding new version, but please follow up how to add a newer version https://github.com/sclorg/welcome/blob/master/contribution.md#adding-a-new-version

2022-06-06 10:02 UTC, michal-josef-spacek commented
@phracek ha, thank you for doc.

2022-06-07 14:26 UTC, michal-josef-spacek commented
[test]

2022-06-09 07:54 UTC, michal-josef-spacek commented
I updated PR to version with 5.34/Dockerfile.c9s on the place and excluded it in the build/test

2022-06-09 07:54 UTC, michal-josef-spacek commented
[test]

2022-06-09 13:59 UTC, michal-josef-spacek commented
[test-all]

2022-06-14 12:14 UTC, phracek requested changes

2022-06-14 12:14 UTC, phracek commented on 5.34/README.md
> -podman pull ubi8/perl-532
This should remain as ubi8. The README.md file is copied into Red Hat Catalog. Please keep there ubi8. In the whole document.

2022-06-14 13:07 UTC, michal-josef-spacek commented on 5.34/README.md
> -podman pull ubi8/perl-532
@phracek I moved to original version this lines.

2022-06-16 13:01 UTC, phracek requested changes
One last issue. And then we can merge it.

2022-06-16 13:17 UTC, michal-josef-spacek commented on 5.34/README.md
> -Usage in Openshift
I updated README to better version.

2022-06-16 13:17 UTC, michal-josef-spacek commented
[test-all]

2022-06-21 09:58 UTC, phracek approved these changes
LGTM. Thanks. Let's get merge it.

2022-06-21 09:58 UTC, merged