run all openshift4 tests even when one fails
sclorg/s2i-perl-container pull request #245
Opened 2022-06-06 11:25 UTC by zmiklank

2022-06-06 11:41 UTC, zmiklank commented
[test-all]

2022-06-06 13:48 UTC, phracek requested changes

2022-06-06 13:48 UTC, phracek commented on test/run-openshift-remote-cluster
What about adding here `set -e` so we are sure that we have a connection to OpenShift 4 cluster and before tests set `set +e`?

2022-06-07 08:52 UTC, zmiklank commented on test/run-openshift-remote-cluster
IMHO we should treat this differently. E.g., calling exit explicitly, when the login is not successful. That way we at least have the debug message:
 ```oc status || false "It looks like oc is not properly logged in. Exiting the test suite" && TESTSUITE_RESULT=1; exit 1```
 instead of:
 ```oc status || false "It looks like oc is not properly logged in."```

2022-06-07 11:22 UTC, phracek commented on test/run-openshift-remote-cluster
It makes sense. Let's use this way.

2022-06-07 12:29 UTC, zmiklank commented on test/run-openshift-remote-cluster
Addressed in https://github.com/sclorg/container-common-scripts/pull/262. If that is merged I can use the function in this container.

2022-06-07 14:30 UTC, zmiklank commented
Added latest common/ and also added a line for exiting tests, when oc login unsuccessful.
[test-all]

2022-06-07 15:18 UTC, zmiklank commented
[test-all]

2022-06-08 06:09 UTC, zmiklank commented
[test-all]

2022-06-30 08:03 UTC, phracek commented
[test-all]

2022-06-30 11:05 UTC, phracek commented
[test-all]

2022-06-30 11:08 UTC, phracek approved these changes
The changes LGTM. Let's see whether tests are passing.

2022-06-30 11:50 UTC, merged