Perl 5.36 support
sclorg/s2i-perl-container pull request #270
Opened 2023-03-29 13:28 UTC by jplesnik

Add a new version Perl 5.36

2023-03-30 07:53 UTC, phracek requested changes
Thanks for this PR! I hit only one issue during the review. Please address my comment.

2023-03-30 07:53 UTC, phracek commented on 5.36/Dockerfile.fedora
>  FROM quay.io/fedora/s2i-base:36
Based on the https://src.fedoraproject.org/rpms/perl in Fedora 36 is perl-5.34. Can we please use `FROM quay.io/fedora/s2i-base:37`  where is perl-536?

2023-03-30 07:58 UTC, zmiklank commented
@jplesnik  Also could you please remove the merge commit, so we have cleaner git history?

2023-03-30 12:46 UTC, phracek commented
Let's try to test it.

[test]

2023-03-31 10:46 UTC, phracek reviewed
@pkubatrh Can you please help me with README.md issue? WDYT?

2023-03-31 10:46 UTC, phracek commented on 5.36/README.md
> +In this example, we will assume that you are using the `ubi8/perl-536` image, available via `perl:5.36` imagestream tag in Openshift.
`ubi8/perl-536` should be change to `ubi8/perl-532` because there is no plan to have this version in RHEL8.

@pkubatrh WDYT? Am I right?

2023-04-03 11:00 UTC, pkubatrh commented on 5.36/README.md
> +In this example, we will assume that you are using the `ubi8/perl-536` image, available via `perl:5.36` imagestream tag in Openshift.
I would move it to `ubi9/perl-536` instead. The README should be for the 5.36 version, I do not think it makes sense to have a different version of the image in there, even if it exists and the current version one does not.
I recommend moving to ubi9 instead of ubi8 for the sole reason that RHEL9 is more likely to receive new versions of Perl in future.

2023-04-04 10:34 UTC, phracek commented
[test-all]

2023-04-04 13:50 UTC, phracek approved these changes
All changes are addressed. Thank you for this pull request and the new perl version to Fedora containers land.

RHEL7 and RHEL OpenShift 4 failures are not affected by this pull request.

2023-04-04 13:52 UTC, merged